# Documentation: https://gohugo.io/configuration/introduction/#configuration-directory

baseURL = "http://schitul-mironesti.localhost/"
# website title
title = "Schitul Mironești"

# website copyright
copyright = "© 2023 Schitul Mironești"

# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultcontentlanguage = "ro"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "ro-RO"

# all languages are generated in folders
defaultContentLanguageInSubdir = false

# language name ["English", "简体中文", "Français", "Polski", ...]
LanguageName = "Română"

# this is used to bail out of recursive content generation
timeout = '200s'

# cleans the destination dir before building
cleanDestinationDir = true

# whether to use robots.txt
enableRobotsTXT = true

# to make the .Lastmod function work
enableGitInfo = true

# whether to show the table of contents in the article
tableOfContents = true

# whether to show the framework used in header
disableHugoGeneratorInject  = false

# whether to use emoji code
enableEmoji = true

# transliterate non-ASCII characters when generating URLs
removePathAccents = true
